
CREATE OR REPLACE RULE hub_insert_1
    AS ON INSERT TO hub WHERE NEW.id BETWEEN 0 AND 99999
    DO INSTEAD INSERT INTO part1 VALUES (NEW.id, NEW.value);
CREATE OR REPLACE RULE hub_insert_2
    AS ON INSERT TO hub WHERE NEW.id BETWEEN 100000 AND 199999
    DO INSTEAD INSERT INTO part2 VALUES (NEW.id, NEW.value);
CREATE OR REPLACE RULE hub_insert_3
    AS ON INSERT TO hub WHERE NEW.id BETWEEN 200000 AND 299999
    DO INSTEAD INSERT INTO part3 VALUES (NEW.id, NEW.value);
CREATE OR REPLACE RULE hub_insert_4
    AS ON INSERT TO hub WHERE NEW.id BETWEEN 300000 AND 399999
    DO INSTEAD INSERT INTO part4 VALUES (NEW.id, NEW.value);
CREATE OR REPLACE RULE hub_insert_5
    AS ON INSERT TO hub WHERE NEW.id BETWEEN 400000 AND 499999
    DO INSTEAD INSERT INTO part5 VALUES (NEW.id, NEW.value);
CREATE OR REPLACE RULE hub_insert_6
    AS ON INSERT TO hub WHERE NEW.id BETWEEN 500000 AND 599999
    DO INSTEAD INSERT INTO part6 VALUES (NEW.id, NEW.value);
CREATE OR REPLACE RULE hub_insert_7
    AS ON INSERT TO hub WHERE NEW.id BETWEEN 600000 AND 699999
    DO INSTEAD INSERT INTO part7 VALUES (NEW.id, NEW.value);
CREATE OR REPLACE RULE hub_insert_8
    AS ON INSERT TO hub WHERE NEW.id BETWEEN 700000 AND 799999
    DO INSTEAD INSERT INTO part8 VALUES (NEW.id, NEW.value);
CREATE OR REPLACE RULE hub_insert_9
    AS ON INSERT TO hub WHERE NEW.id BETWEEN 800000 AND 899999
    DO INSTEAD INSERT INTO part9 VALUES (NEW.id, NEW.value);
CREATE OR REPLACE RULE hub_insert_10
    AS ON INSERT TO hub WHERE NEW.id BETWEEN 900000 AND 999999
    DO INSTEAD INSERT INTO part10 VALUES (NEW.id, NEW.value);